spring.application.name=medication-reminder
server.port=8081

# H2 databas
spring.datasource.url=jdbc:h2:file:./data/medicinedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA inställningar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console